services:
  - type: web
    name: escuela
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn escuela.wsgi"
    preDeployCommand: "python manage.py migrate && python manage.py collectstatic --noinput"
